import pyqrcode

seeds = [
  "EWRTZJHGSDGTRHNGVDISUGHIFVDJFERHUFBGRZEUFSDHFEGBRVHISDJIFUBUHVFDSHFUERIBUJHDRGBCG",
  "NFTRKXZHCJUUSMBCRSHMHHHDBKNKQQFOWZZQXXIUXKIDJPUGEEZJPEROMAFKBA9XWZUJUURGT9YFXXYEQ"
]

for seed in seeds:
    qr = pyqrcode.create(seed)
    qr.svg(seed+".svg", scale=8)